version: '3'
services:
  frontend:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/frontend
      - node_modules:/usr/src/frontend/node_modules
    command: sh -c "yarn start"
    ports:
      - '3000:3000'
volumes:
  node_modules:
    driver: local
