name: E2E Test

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v2.7.0
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          spec: cypress/integration/game.spec.ts
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: react-reversi-gh
          SLACK_TITLE: CI Test Success
          SLACK_MESSAGE: 'E2E Test Passed! :rocket:'
          SLACK_COLOR: good
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: react-reversi-gh
          SLACK_TITLE: CI Test Failure
          SLACK_MESSAGE: 'E2E Test Failed! :boom:'
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
