name: Lint Check

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  lint-check-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Lint Check run
        run: yarn lint
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: react-reversi-gh
          SLACK_TITLE: CI Test Success
          SLACK_MESSAGE: 'Lint Check Passed! :rocket:'
          SLACK_COLOR: good
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: react-reversi-gh
          SLACK_TITLE: CI Test Success
          SLACK_MESSAGE: 'Lint Check Failed! :boom:'
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
