name: Unit Test

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Unit test run
        run: yarn test
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: react-reversi-gh
          SLACK_TITLE: CI Test Success
          SLACK_MESSAGE: 'Unit Test Passed! :rocket:'
          SLACK_COLOR: good
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: react-reversi-gh
          SLACK_TITLE: CI Test Failure
          SLACK_MESSAGE: 'Unit Test Failed! :boom:'
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
